---
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: .
    dir: ./gopls
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.xz]
    # only binary, do not include any additional files
    files:
      - not-exists*
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}-{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
