---
name: Schedule

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/scheduler.yml
      - scheduler.py
  schedule:
    - cron: 0 8 * * *

permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install python packages
        run: pip install requests

      - name: Scheduler
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          python scheduler.py

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: gautamkrishnar/keepalive-workflow@v2
